//bai 1
CREATE USER C##BAITHI IDENTIFIED BY 123;
GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE TO C##BAITHI;
CONN C##BAITHI/123;

CREATE TABLE TUYEN (
    MATUYEN VARCHAR2(10) PRIMARY KEY,
    BENDAU VARCHAR2(50),
    BENCUOI VARCHAR2(50),
    GIATUYEN NUMBER,
    NGXB DATE,
    TGDK NUMBER
);


CREATE TABLE XE (
    MAXE VARCHAR2(10) PRIMARY KEY,
    BIENKS VARCHAR2(20),
    MATUYEN VARCHAR2(10),
    SOGHET1 NUMBER,
    SOGHET2 NUMBER,
    CONSTRAINT FK_XE_TUYEN FOREIGN KEY (MATUYEN) REFERENCES TUYEN(MATUYEN)
);


CREATE TABLE KHACH (
    MAHK VARCHAR2(10) PRIMARY KEY,
    HOTEN VARCHAR2(100),
    GIOITINH VARCHAR2(10),
    CMND VARCHAR2(20)
);

CREATE TABLE VEXE (
    MATUYEN VARCHAR2(10),
    MAHK VARCHAR2(10),
    NGMUA DATE,
    GIAVE NUMBER,
    PRIMARY KEY (MATUYEN, MAHK, NGMUA),
    CONSTRAINT FK_VEXE_TUYEN FOREIGN KEY (MATUYEN) REFERENCES TUYEN(MATUYEN),
    CONSTRAINT FK_VEXE_KHACH FOREIGN KEY (MAHK) REFERENCES KHACH(MAHK)
);

//2

INSERT INTO TUYEN VALUES ('T11A', 'SG', 'DL', 210000, TO_DATE('26/12/2016','DD/MM/YYYY'), 6);
INSERT INTO TUYEN VALUES ('T32D', 'PT', 'SG', 120000, TO_DATE('30/12/2016','DD/MM/YYYY'), 4);
INSERT INTO TUYEN VALUES ('T06F', 'NT', 'DNG', 225000, TO_DATE('02/01/2017','DD/MM/YYYY'), 7);


INSERT INTO KHACH VALUES ('KH01', 'Lâm Văn Bền', 'Nam', '655615896');
INSERT INTO KHACH VALUES ('KH02', 'Dương Thị Lục', 'Nữ', '275648642');
INSERT INTO KHACH VALUES ('KH03', 'Hoàng Thanh Tùng', 'Nam', '456889143');


INSERT INTO VEXE VALUES ('T11A', 'KH01', TO_DATE('20/12/2016','DD/MM/YYYY'), 210000);
INSERT INTO VEXE VALUES ('T32D', 'KH02', TO_DATE('25/12/2016','DD/MM/YYYY'), 144000);
INSERT INTO VEXE VALUES ('T06F', 'KH03', TO_DATE('30/12/2016','DD/MM/YYYY'), 270000);


//3
ALTER TABLE TUYEN ADD CONSTRAINT CK_GIA_THOIGIAN 
CHECK (NOT (TGDK > 5 AND GIATUYEN <= 200000));
//4
CREATE OR REPLACE TRIGGER TRG_GIAVE_TET
BEFORE INSERT OR UPDATE ON TUYEN
FOR EACH ROW
BEGIN
    IF :NEW.NGXB BETWEEN TO_DATE('29/12/2016','DD/MM/YYYY') AND TO_DATE('05/01/2017','DD/MM/YYYY') THEN
        :NEW.GIATUYEN := :NEW.GIATUYEN * 1.2;
    END IF;
END;
/

//5
SELECT * FROM VEXE 
WHERE EXTRACT(MONTH FROM NGMUA) = 12 
ORDER BY GIAVE DESC;
//6
SELECT MATUYEN 
FROM VEXE 
WHERE EXTRACT(YEAR FROM NGMUA) = 2016
GROUP BY MATUYEN
HAVING COUNT(*) = (
    SELECT MIN(COUNT(*)) 
    FROM VEXE 
    WHERE EXTRACT(YEAR FROM NGMUA) = 2016 
    GROUP BY MATUYEN
);

//7
SELECT MATUYEN 
FROM VEXE V JOIN KHACH K ON V.MAHK = K.MAHK
WHERE K.GIOITINH = 'Nam'
INTERSECT
SELECT MATUYEN 
FROM VEXE V JOIN KHACH K ON V.MAHK = K.MAHK
WHERE K.GIOITINH = 'Nữ';

//8
SELECT * FROM KHACH K
WHERE GIOITINH = 'Nữ' AND NOT EXISTS (
    SELECT MATUYEN FROM TUYEN
    MINUS
    SELECT MATUYEN FROM VEXE V WHERE V.MAHK = K.MAHK
);

