//1
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE; 

CREATE USER BAITHI IDENTIFIED BY 123;
GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE TO BAITHI;


CONN BAITHI/123;


CREATE TABLE USERS (
    UID_ NUMBER PRIMARY KEY,
    USERNAME VARCHAR2(100),
    PASS VARCHAR2(100),
    REGDAY DATE DEFAULT SYSDATE, 
    NATIONALITY VARCHAR2(50)
);


CREATE TABLE CHANNEL (
    CHANNELID VARCHAR2(10) PRIMARY KEY,
    CNAME VARCHAR2(100),
    SUBSCRIBES NUMBER,
    OWNER NUMBER,
    CREATED DATE,
    CONSTRAINT FK_CHANNEL_USER FOREIGN KEY (OWNER) REFERENCES USERS(UID_)
);


CREATE TABLE VIDEO (
    VIDEOID VARCHAR2(10) PRIMARY KEY,
    TITLE VARCHAR2(200),
    DURATION NUMBER,
    AGE NUMBER
);


CREATE TABLE SHARE (
    VIDEOID VARCHAR2(10),
    CHANNELID VARCHAR2(10),
    PRIMARY KEY (VIDEOID, CHANNELID),
    CONSTRAINT FK_SHARE_VIDEO FOREIGN KEY (VIDEOID) REFERENCES VIDEO(VIDEOID),
    CONSTRAINT FK_SHARE_CHANNEL FOREIGN KEY (CHANNELID) REFERENCES CHANNEL(CHANNELID)
);

//2
INSERT INTO USERS VALUES (001, 'faptv', '123456abc', TO_DATE('01/01/2014','DD/MM/YYYY'), 'Việt Nam');
INSERT INTO USERS VALUES (002, 'kemxoitv', '@147869iii', TO_DATE('05/06/2015','DD/MM/YYYY'), 'Campuchia');
INSERT INTO USERS VALUES (003, 'openshare', 'qwertyuiop', TO_DATE('12/05/2009','DD/MM/YYYY'), 'Việt Nam');


INSERT INTO CHANNEL VALUES ('C120', 'FAP TV', 2343, 001, TO_DATE('02/01/2014','DD/MM/YYYY'));
INSERT INTO CHANNEL VALUES ('C905', 'Kem xôi TV', 1032, 002, TO_DATE('09/07/2015','DD/MM/YYYY'));
INSERT INTO CHANNEL VALUES ('C357', 'OpenShare Cafe', 5064, 003, TO_DATE('10/12/2010','DD/MM/YYYY'));


INSERT INTO VIDEO VALUES ('V100229', 'FAPtv Cơm Nguội Tập 41', 469, 18);
INSERT INTO VIDEO VALUES ('V211002', 'Kem xôi: Tập 31', 312, 16);
INSERT INTO VIDEO VALUES ('V400002', 'Nơi tình yêu kết thúc', 378, 0);


INSERT INTO SHARE VALUES ('V100229', 'C905');
INSERT INTO SHARE VALUES ('V211002', 'C120');
INSERT INTO SHARE VALUES ('V400002', 'C357');
COMMIT;
//4
CREATE OR REPLACE TRIGGER TRG_CHECK_DATE
BEFORE INSERT OR UPDATE ON CHANNEL
FOR EACH ROW
DECLARE
    V_REGDAY DATE;
BEGIN
    SELECT REGDAY INTO V_REGDAY FROM USERS WHERE UID_ = :NEW.OWNER;
    IF :NEW.CREATED < V_REGDAY THEN
        RAISE_APPLICATION_ERROR(-20001, 'Ngày tạo kênh phải >= ngày đăng ký người dùng.');
    END IF;
END;
/
//5
SELECT * FROM VIDEO WHERE AGE >= 16;
//6
SELECT * FROM CHANNEL WHERE SUBSCRIBES = (SELECT MAX(SUBSCRIBES) FROM CHANNEL);
//7
SELECT V.VIDEOID, V.TITLE, COUNT(S.CHANNELID) AS SO_KENH_SHARE
FROM VIDEO V LEFT JOIN SHARE S ON V.VIDEOID = S.VIDEOID
WHERE V.AGE = 18
GROUP BY V.VIDEOID, V.TITLE;
//8
SELECT * FROM VIDEO V
WHERE NOT EXISTS (
    SELECT CHANNELID FROM CHANNEL
    MINUS
    SELECT CHANNELID FROM SHARE S WHERE S.VIDEOID = V.VIDEOID
);